spring:
  application:
    name: spring-app-sample
  cloud:
    azure:
      active-directory:
        enabled: true
        session-stateless: false
        profile:
          tenant-id: ${AZURE_AD_TENANTID}
        credential:
          client-id: ${AZURE_AD_CLIENTID}
          client-secret: ${AZURE_AD_CLIENTSECRET}
        app-id-uri: ${AZURE_AD_APPURI}
